### ISSUE TITLE
about SHL datasets

### ISSUE THREAD

**Issue by yekai1111111** [getalp/Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices#3]
Hello, I encountered this problem when running DATA_SHL.py, what should I do to solve it,thank you.
    problem:File "F:\Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices-main\datasets\DATA_SHL.py", line 272, in <module>
       userData = np.asarray(userData)
       ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2        dimensions. The detected shape was (9, 4) + inhomogeneous part.

**Comment by Sannaraek** [comment]
Hello, 

Thank you for bringing attention to this matter.

This is because the numpy version used for the development at the time accepted this line, while the up-to-date numpy version today no longer do.

If you would like to use the provided scripts with a higher version of numpy, you can add 'dtype=object' as a flag to the np.asarray function. Eg: np.array(userData, dtype=object) 

In anycase, I've also updated the scripts to support a higher version of numpy. 
Please pull the latest commit
