### ISSUE TITLE
Inhomogeneous Shape Error when trying to create the Realworld Dataset

### ISSUE THREAD

**Issue by mnsh222** [getalp/Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices#4]
Hello, 
I am currently unable to fix the following issue for running the code of datasets/dataset/DATA_REALWORLD.py
Line 263     clientsAccDataByOrientation.append(np.asarray(xAccListClient))

throws the following error: 
"ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (15,) + inhomogeneous part."

Debugging shows that xAccListClient is a list of ndarrays with the dimensions (x, 128, 3), where x is a value in the range 3000 to 4000. 
I have used the dataset downloaded in the code and also am using Python 3.7.

**Comment by Sannaraek** [comment]
Hello,

Thank you pointing this issue out!

This seems related to a previous issue opened 
https://github.com/getalp/Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices/issues/3

"This is because the numpy version used for the development at the time accepted this line, while the up-to-date numpy version today no longer do.

If you would like to use the provided scripts with a higher version of numpy, you can add 'dtype=object' as a flag to the np.asarray function. Eg: np.array(userData, dtype=object)"

I believe this line was missed in the previous commit iteration, I've updated the scripts accordingly.

Please pull the latest commit

Best

**Comment by mnsh222** [comment]
Hello, 
thank you for your fast reply! I pulled the latest commit and wanted to execute it. However, I received another error in line 327: 

np.asarray([np.dstack((normAcc, normGyro), dtype=object) for normAcc, normGyro in zip(normAcc, normGyro)]))
TypeError: dstack() got an unexpected keyword argument 'dtype'

Removing "dtype=object" from this line leads to the inhomogeneous error again, so now I am wondering why dstack is used?

**Comment by Sannaraek** [comment]
Hello,

Thank you again for pointing this out!

I believe it's due to a wrong placement in dtype=object here, please try the script below or pull the latest commit

    stackedOrientationData.append(np.asarray([np.dstack((normAcc,normGyro)) for normAcc,normGyro in zip(normAcc,normGyro)],dtype=object))

Dstack is used to combine the accelerometer and gyroscope back into one variable since they first had to be separated to be normalized independently per sensor.

Best
