### ISSUE TITLE
Error with fitting the history and hint for MobileHART

### ISSUE THREAD

**Issue by mnsh222** [getalp/Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices#5]
First, I wanted to execute MobileHART for the RealWorld data set, however, the first issue I ran into was that in 
line 398 in main.py:
_model_classifier = model.mobileHART_XS(input_shape,activityCount,convKernels = convKernels)_ 
convKernels needs to be removed from the parameters as mobileHART does not take convKernels as input parameter.

Afterwards, I run into a second issue for both HART and MobileHART in line 420:
_history = model_classifier.fit(_
I get a Tensorflow InvalidArgumentError, as there seems to be a "Graph execution error".
The reason provided is that "Conv2DCustomBackpropFilterOp only supports NHWC." Why does this happen?

**Comment by Sannaraek** [comment]
Hello,

Thank you for pointing out the issue!

This has been addressed with the related update.

Regarding your 2nd issue 
 "Conv2DCustomBackpropFilterOp only supports NHWC."

This error only appear when MobileHART is trained on CPU, as mentioned in the readme, please use GPU to train the models.

This is due to a unsupported behavioral problem of a specific convolutional layer which HART and MobileHART uses from tensorflow.

Best of luck!
